[package]
name = "youdao"
version = "0.1.0"
authors = ["alen <to_alen@sina.com>"]

[dependencies]
html5ever = "*"
scraper = "*"
regex = "*"
glib = "*"
gdk = "*"
gdk-pixbuf = "*"
gtk = "*"
cairo-rs = "*"
time = "*"
serde_json = "*"
base64 ="*"
reqwest = "*"